### ISSUE TITLE
Building ableC should use the silver branch of the same name, if possible

### ISSUE THREAD

**Issue by krame505** [melt-umn/jenkins-lib#11]
Similarly to how building an extension on a branch will use ableC on that branch if it exists, if we are using ableC on a branch then we should use silver (both sources and jars) from that branch as well, if possible.  Currently building a branch on silver will result in downstream builds on that branch happening correctly, but pushing directly to an ableC branch will trigger a build using the default version of silver and fail as a result.  The same is the case for silver-ableC.  
I'm not exactly sure what needs to happen to fix this.  But presumably the logic in Silver's Jenkinsfile that figures out where to find the jars should move to the library?  Seems like we should maybe create a new `silver.groovy` file for this sort of thing (and move `getSilverEnv()` there, too.)

**Comment by krame505** [comment]
I think I'm going to take a stab at fixing this.  @tedinski is there any strong reason why we use `/export/scratch/melt-jenkins/custom-silver` and don't just check out a fresh copy of silver for every build (unless an explicit `SILVER_BASE` parameter is given?)

**Comment by tedinski** [comment]
Simple, fast, works?

I wouldn't change things to always check out by default.

**Comment by krame505** [comment]
OK, I'll make it still use custom-silver when building master and develop, or when a silver branch of that name doesn't exist, and only do the checkout otherwise.

**Comment by krame505** [comment]
I think I fixed this, if you want to take a look at the changes.

**Comment by tedinski** [comment]
I glanced briefly at the changes, they look ok, as long as things are actually working in Jenkins, then it looks like this issue is resolved to me.

**Comment by krame505** [comment]
OK, this seems to be working for the `feature/reflection` branch so I'm closing this.
