### ISSUE TITLE
Jenkins not triggering automatically?

### ISSUE THREAD

**Issue by krame505** [melt-umn/jenkins-lib#16]
Something seems to be screwed up with Jenkins, it doesn't seem to be recognizing new branches pushed to Silver until I manually hit "Scan Repository Now".  This seems to have started being an issue in the last week or so.  Did anything change/get updated with Jenkins in that time frame?  
@tedinski

**Comment by krame505** [comment]
Also it seems to have not recognized some commits to existing branches until manually scanned: http://coldpress.cs.umn.edu:8080/job/melt-umn/job/silver/indexing/console

**Comment by ericvanwyk** [comment]
Besides this immediate problem, there were some problems with coldpress and system staff suggested replacing the hard disk.  We didn't have to do this (Louis realized the networking lights on coldpress were funky and tracked down the problem to a faulty pocket switch and replaced it with another one lying around - problem solved) but what if we did?

Is the Jenkins stuff backed up anywhere?

Is there some online service we could transfer all of Jenkins code to instead?

We can get a VM set up to do this as well, though it may not be as beefy as coldpress so maybe we don't want that.

Any thoughts?

**Comment by RandomActsOfGrammar** [comment]
Jenkins has the following message:
```
There were some problems while registering or removing one or more GitHub webhooks.
```
When you click to view the problems, you get a table with what appears to be a large number of the Jenkins projects with the error message
```
There are no credentials with admin access to manage hooks on GitHubRepositoryName[host=github.com,username=melt-umn,repository=<repository name>]
```
This would seem to explain why it doesn't get new commits or new branches.

**Comment by tedinski** [comment]
I believe it's a firewall configuration issue, and I've sent an email to operator about fixing it. Hopefully everything will come back once that's resolved.

That said, repos should also get scanned once a day, and Jenkins wasn't doing that. (I triggered Silver manually, but the log before that was July 2.) I can't explain that.

**Comment by tedinski** [comment]
Operator fixed the firewall, and it seems to be working. Notes for future reference available here: 

https://github.com/melt-umn/jenkins-lib/blob/master/Github-Webhooks-Firewall.md

**Comment by krame505** [comment]
Looks like this broke yet again.  From the log:
```
Failed to add GitHub webhook for GitHubRepositoryName[host=github.com,username=melt-umn,repository=silver-ableC]
java.lang.NullPointerException: There are no credentials with admin access to manage hooks on GitHubRepositoryName[host=github.com,username=melt-umn,repository=silver-ableC]
```

However the Github CIDR ranges posted at https://api.github.com/meta don't seem to have changed, per the above debugging guide from Ted.  

Any ideas on how to proceed?

**Comment by krame505** [comment]
Seems that this has fixed itself on its own, as builds are being triggered on push events.  The issue with NFS (#17) is still causing ableC builds to fail.

**Comment by krame505** [comment]
Reopening since this seems to have broken again - merging https://github.com/melt-umn/silver/pull/369 did not trigger an automatic build.  Probably the firewall issue resurfacing again.

**Comment by krame505** [comment]
Took another look at this, doesn't seem to be a firewall problem (?)
On http://coldpress.cs.umn.edu:8080/administrativeMonitor/GitHubHookRegisterProblemMonitor/ we have errors for every repository of the form `There are no credentials with admin access to manage hooks on GitHubRepositoryName[host=github.com,username=melt-umn,repository=ableC-tensor-algebra]`.
On https://github.com/organizations/melt-umn/settings/hooks/9479568 every recent item is showing the error `We couldn’t deliver this payload: failed to connect`.

I'm not sure on how to proceed from here, should we contact the systems staff again?

**Comment by krame505** [comment]
The problem was indeed the firewall, looks like the configuration got overwritten at some point.  Operator has fixed this, and builds seem to be triggering again.

**Comment by ericvanwyk** [comment]
Glad it is working again.
