### ISSUE TITLE
Nailgun installation missing

### ISSUE THREAD

**Issue by krame505** [melt-umn/jenkins-lib#17]
The ableC build on Jenkins is failing because it can't find the jars for nailgun - it seems that the /project/melt* workspaces on coldpress have disappeared?  

`sv-nailgun` also checks under /usr/share/java for the jar, however I don't seem to have permissions to copy things there.  Do we need to contact operator about this?

**Comment by krame505** [comment]
For reference, the [sv-nailgun](https://github.com/melt-umn/silver/blob/develop/support/nailgun/sv-nailgun) script is hardcoded to look in the following locations: `/project/melt4/People/ted/nailgun/bin/nailgun-*.jar /usr/share/java/nailgun-server*.jar /usr/share/java/nailgun-*.jar`

It seems that the jars were formerly in the first one, and this directory no longer exists.  I could change this temporarily to check in a directory that I own, but I'm not sure if that is the best fix.  

@ericvanwyk What happened to the `/project/melt*` folders?  Were these intentionally deleted?

**Comment by ericvanwyk** [comment]
Those folders should be there.  Probably just a hiccup with NFS.  I'll email operator and ask.

**Comment by krame505** [comment]
Folders are still missing, meaning this probably isn't a momentary glitch.  Any suggestions on how to work around this for the moment so Jenkins can start working again?  I tried putting a nailgun jar in `/usr/share/java` but it seems I lack write permissions.  

Unless someone has a better idea, I can change the sv-nailgun script to look for the nailgun jar in a place that the gitbot user can access.

**Comment by ericvanwyk** [comment]
It is taking some time for systems to reboot the machine, so you can try
that.

Thanks.

**Comment by krame505** [comment]
Based on uptime it appears that coldpress was rebooted 24 hours ago, apparently with no effect.  I will try making the above workaround change tonight if I get around to it.

**Comment by ericvanwyk** [comment]
yep, the systems people noticed this too.  They've elevated the issue to
the systems staff that are more experienced.

**Comment by krame505** [comment]
As a workaround I put a copy of nailgun in /export/scratch, to hopefully at least get builds passing again.  However this is not a fix that is suitable for the long term.

#16 means that builds still aren't triggering properly on push events, someone needs to contact the systems staff about this as well.

**Comment by krame505** [comment]
After multiple attempts and hours debugging, I have come to realize that the intricacies of nailgun are much more than I thought - I am giving up on a "quick workaround".  Not being able to view exactly what files are missing is part of the problem...

Hopefully the missing folders can be recovered soon by the systems people.

**Comment by ericvanwyk** [comment]
Thanks for trying Lucas.  I've just sent them a more strongly worded email.  I don't know if they will get to this on the weekend however.  I'll remind them on Tuesday if I haven't heard anything.  Please keep me in the loop about this - especially if you notice something changing.

**Comment by ericvanwyk** [comment]
I've emailed again - using stronger language.

**Comment by krame505** [comment]
It appears that this is also causing most of the ableC extension builds to fail, as they are unable to find the Boehm GC library.
