### ISSUE TITLE
Extension develop branch build still being triggered after failure in extension feature branch

### ISSUE THREAD

**Issue by krame505** [melt-umn/jenkins-lib#2]
For example, I'm not sure why http://coldpress.cs.umn.edu:8080/job/melt-umn/job/ableC-sqlite/job/develop/120/ was triggered by http://coldpress.cs.umn.edu:8080/job/melt-umn/job/ableC/job/feature%252Fenv/31/.  Note that the extension feature branch was built as well, and failed: http://coldpress.cs.umn.edu:8080/job/melt-umn/job/ableC-sqlite/job/feature%252Fenv/15/.  

This is kinda hard to reproduce, but... any thoughts?  Or maybe I'm missing something.

**Comment by tedinski** [comment]
Should have been fixed last week.
