### ISSUE TITLE
Allow for artifacts to be maintained between builds

### ISSUE THREAD

**Issue by krame505** [melt-umn/jenkins-lib#3]
To develop a branch of Silver with bootstrapped changes, we really need the ability to manually specify new jars to use for a branch.  This can sometimes be made nicer (and sometimes avoided) if we separately maintain the most recent successfully-built jars corresponding to each branch, and use them the next time that branch is built.  
Finally, when merging a feature branch that depends on new jars, the jars from the feature branch are needed instead of the jars from `develop`, or otherwise there will immediately be a build failure when merging (same is true for `develop` -> `master`.)  Note that we can't always just use the jars from the source branch to build the target branch (e.g. merging `develop` back into a feature branch.)  

Basically, what I am envisioning is this:
* Every new branch that is successfully built has a corresponding new folder created at some static location, containing the resulting jars.
* We have a build parameter of from what branch to use the jars - this is empty by default, indicating to use jars from the 'default' branch.
  * If we are building `develop` or `master`, and the last commit was a merge commit - use jars from the branch being merged.
    * I'm sure this is possible to figure out with some clever git commands and `grep`.
  * Otherwise if the jars folder for the current branch exists - use these jars;
  * Otherwise - use jars from `develop`;
* Add a script in Silver that `scp`s the current jars into the Jenkins folder for the current branch.

So essentially,
1. With our normal workflow, the right thing usually happens;
2. When merging in the other direction, the build will occasionally fail on a feature branch, which we can fix by manually triggering a build with jars from a different branch;
3. If we are bootstrapping a new feature (or things ever really go wrong - e.g. two feature branches are both bootstrapped independently, and neither can build the other), we can always just upload new jars to use.

**Comment by tedinski** [comment]
> Every new branch that is successfully built has a corresponding

I'll probably try using jenkin's artifact archiving feature instead. Hopefully it'll work for this purpose.

> I'm sure this is possible to figure out with some clever git commands and grep.

If you figured those out for me, it'd help accelerate my getting this done on thursday.

> merge commit

Can you think of any major problems with this heuristic:

1. If OVERRIDE_JARS is set, use those.
2. If the current branch is 'master' or 'develop' and the last commit was a merge, use that branch's jars if any.
3. If the current branch has a last successful build with artifacts, use those.
4. Use fetch-jars

**Comment by krame505** [comment]
> I'll probably try using jenkin's artifact archiving feature instead. Hopefully it'll work for this purpose.

I wasn't familiar with that, seems reasonable.  

> If you figured those out for me, it'd help accelerate my getting this done on thursday.

I'll try to take a look tonight.

> Can you think of any major problems with this heuristic:

Yeah, that's mostly what I had in mind.  Would `OVERRIDE_JARS` then be an absolute path name on coldpress?  If that is the case then uploading new jars could get slightly painful.  It seems Jenkins does have a way of specifying files to upload directly ('file parameters), although it is a bit buggy (but there apparently is a workaround: https://bitbucket.org/janvrany/jenkins-27413-workaround-library).

**Comment by krame505** [comment]
Turns out it's super simple!  All you need is
```for branch in $(git show --no-patch --format="%P" HEAD | awk '{print $2}' | xargs git branch --contains | grep '^[^*].*' | cut -c 3-); do echo "$(git log --format=%B -n 1 HEAD)" | grep -o "$branch"; done | awk '{ print length($0) " " $0; }' | sort -r -n | head -n 1 | cut -d ' ' -f 2```

`git show --no-patch --format="%P" HEAD` prints the parents of the most recent commit - if there is more than one then it's a merge commit.  If you want you can pipe this to `grep '[^ ]* [^ ]*'` to get a non-empty string iff this is the case.  

Now comes the tricky part - a commit doesn't actually record on what branch it was originally made , and the commit message for the merge commit doesn't have a standard format.  However, you can search for any branch containing the parent commit, filtering out the current branch, to get a list of possible branches.  The actual branch name should occur at least somewhere in the commit message of the merge commit, so we can grep the commit message for every branch that has the commit in question, sort the matching branch names by length, and take the longest one.

**Comment by tedinski** [comment]
Hmm. I tried testing that out a bit and it seemed slightly unreliable.

Since the common case we want to handle is merging pull requests into develop, I think what I might do is just match on the commit message. See if it matches `^Merge.*from (.*)`

**Comment by krame505** [comment]
Huh, I did test this out a bit.  What did you find that didn't work?

**Comment by tedinski** [comment]
I'm not even sure anymore, I think one of them was TOO successful: a merge from a branch to another branch would return a value but I thought it kinda shouldn't...

At any rate, I think just looking at commit message works, since that approach also looked at commit messages anyway...

**Comment by krame505** [comment]
The idea was that you know what branch you are *currently* on (i.e. what branch you are building), and can check explicitly that you are on `master` or `develop`.  If you then see the last commit was a merge, then you know that a certain branch was just merged into `master` or `develop`.  Of course, this would also recognize a merge commit that was made on a different branch and fast-forwarded, but then using that branches jars would be the right behavior anyway (and just checking the commit message would have the same result, too.)  

I suppose just checking the commit message for a PR merge should work for our usual workflow.  There are times when I've needed to merge something locally and push it when something is broken, and recognizing local merges might make testing this easier.  But I guess I am fine with either way.

**Comment by tedinski** [comment]
Could you:

1. Merge current develop into your branch
2. Get a working copy checked out on coldpress, if you don't have one already
3. run `support/jenkins/override_jars_path.sh` to find the path to give jenkins (plus get any errors about permissions to fix, so jenkins can read them)
4. (Probably in order for jenkins to notice the new parameters, rebuild your branch once to fail immediately)
5. Um, wait 20 min or so (from time of my posting) for Jenkins to quiet down from building 'develop'
6. Manually rebuild and set the `OVERRIDE_JARS` parameter to the path value the script output.

Everything's probably broken, so dunno if this will succeed yet, but it might! The inability to properly test Jenkinsfiles annoys me.

Once that actually works, the next step is to make another commit on that branch, to see if it picks up jars from previous builds.

Once that works, the next step is to merge the pull request, and see if the jars get copied over from the original branch to develop.

**Comment by tedinski** [comment]
I guess just to make sure... uh, Step 2.5. Make sure it has the bootstrapped jars in it and builds successfully for you.

**Comment by tedinski** [comment]
It probably doesn't help you much that I went and bogged jenkins down again. :laughing:

**Comment by tedinski** [comment]
It doesn't find out about parameters until the script has a chance to run and set the job's parameters.

Since I added `OVERRIDE_JARS` since you last build it, it won't show up in the UI the first time, unless it's way smarter than I thought.

**Comment by krame505** [comment]
Ah, that's what you mean.  Well, I just did that when I merged develop into my branch.  No problem as long as this is a one-time thing.

**Comment by krame505** [comment]
And it failed: http://coldpress.cs.umn.edu:8080/job/melt-umn/job/silver/job/feature%252Freflection/12/

I think there is something wrong with the permissions checking for each individual jar?

**Comment by tedinski** [comment]
Okay, I see I forgot to check to make sure the files themselves are readable. Fix that, try again, I'll go add something to the script to also check for that. :)

`chmod o+r jars/*.jar`

**Comment by tedinski** [comment]
Looks like some tutorials failed for some reason?

Unfortunately, until a build actually succeeds you'll have to manually do `OVERRIDE_JARS` each re-attempt. That's unfortunate. I wonder if I should make it more aggressively re-use artifacts from previous builds?

**Comment by krame505** [comment]
Hmm, that would be nice in some cases.  But if you accidently gave it the wrong jars then it would just keep failing... I guess that might not be so bad.  Although I don't know if we want to keep failed jars archived - is there a way to just have the build parameter default to whatever it was previously when a build fails, and just change it back to 'no' when a build succeeds?

**Comment by tedinski** [comment]
No easy way to do that I can see. I might be able to make it only archive jars if it makes it past the initial build, though. (Not exactly sure how jenkins behaves.) So even if it's taking jars from "failed" builds it'll be only from builds that did successfully build itself at least.

**Comment by krame505** [comment]
OK, I guess that is good enough for now.

**Comment by tedinski** [comment]
Once you've had a chance to work this through and (hopefully) merge the reflection stuff today, let me know if this seems to be working for you.

**Comment by krame505** [comment]
Sure.  BTW did you get around to implementing the thing where we still archive the jars if the downstream builds fail?

**Comment by tedinski** [comment]
Oh. No, it started looking like it was a difficult thing to do, unfortunately.

It seems like it picks a build then tries to get artifacts. So there's no obvious "last build with artifacts" it can find.

**Comment by krame505** [comment]
I thought the idea was that the most recent build would still have artifacts, even if the integration failed.  What I am seeing is that even when the most recent build failed in integration, the next build doesn't find any artifacts in the previous build.

**Comment by krame505** [comment]
Actually, nevermind.  That might have been because the last build to pass the test phase was before I merged in the recent-ish Jenkins changes from `develop`.

**Comment by krame505** [comment]
Hmm, maybe there is actually an issue here: http://coldpress.cs.umn.edu:8080/job/melt-umn/job/silver/job/feature%252Freflection/18/ passed the test phase and has associated artifacts.  Why didn't http://coldpress.cs.umn.edu:8080/job/melt-umn/job/silver/job/feature%252Freflection/19/ find these artifacts?

**Comment by tedinski** [comment]
> Oh. No, it started looking like it was a difficult thing to do, unfortunately.
>
> It seems like it picks a build then tries to get artifacts. So there's no obvious "last build with artifacts" it can find.

Basically, all copy artifacts can do is follow a simple pointer. Jenkins keeps track of the last successful build, but it does not track the last time a job had artifacts, so it doesn't have a way to find it.

**Comment by tedinski** [comment]
Hmm. I suppose we could try something like "copy artifacts from last successful, then try also copying artifacts from very last build of any kind." Do you think that would work?

**Comment by krame505** [comment]
That is what I thought we were doing, which is why I was confused.

**Comment by tedinski** [comment]
Okay, I'll commit that logic to develop.

**Comment by krame505** [comment]
Everything seems to be working here (it grabbed the right jars after I merged https://github.com/melt-umn/silver/pull/217), so I'm going to go ahead and close this.
